name: 'Coalesce'
description: 'Execute Coalesce Jobs using coa CLI.'
inputs:
  coa-config:
    description: 'coa config file content'
    required: true
  arguments:
    description: "Arguments to pass to coa"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.coa-config }}
    - ${{ inputs.arguments }}
