name: 'Coalesce'
description: 'Execute Coalesce Jobs using'
inputs:
  coa-config:
    description: 'Secret Containing coa config file'
    required: true
  arguments:
    description: "Arguments to pass to coa"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.coa-config }}
    - ${{ inputs.arguments }}
