name: Create tag
on:
  push:
    branches:
      - main
jobs:
  create-tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jefflinse/pr-semver-bump@v1
        name: Create tag
        with:
          mode: bump
          repo-token: ${{ secrets.ACTIONS_TOKEN }}
          with-v: true
